-- Generated by HyprMod

-- Monitors
hl.monitor({
    output = "DP-3",
    disabled = false,
    mode = "1920x1080@180.00Hz",
    position = "0x0",
    scale = 1,
    bitdepth = 10,
    cm = "srgb",
})

-- Keybinds
hl.unbind("Print")
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("serpantinum screenshot"), {
    locked = true,
})
hl.unbind("SUPER + Print")
hl.bind("ALT + F1", hl.dsp.exec_cmd("serpantinum screenshot --full"), {
    locked = true,
})
